# Generated by Django 5.2.5 on 2025-12-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='is_endless',
            field=models.BooleanField(default=False),
        ),
    ]
